version: '2.0'

networks:
  rede_wordpress:

volumes:
  mysql_vol:

services:
  wordpress:
    container_name: wordpress
    image: wordpress:${WP_VERSION}
    networks:
      - rede_wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: banco_mysql
    env_file:
      - env/wordpress.env

  mysql:
    container_name: banco_mysql
    image: mysql:${MYSQL_VERSION}
    networks:
      - rede_wordpress
    volumes:
      - mysql_vol:/var/lib/mysql
    env_file:
      - env/mysql.env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    networks:
      - rede_wordpress
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: banco_mysql
      PMA_HOST: banco_mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M